services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - base-network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'   # Asosiy port
      - '9001:9001'   # Konsol uchun port
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command:
      server --console-address :9001 /data

networks:
  base-network:
    driver: bridge

volumes:
  pg_data:
    driver: local
  kafka-data:
    driver: local
